//! Reading the packet filter, without needing an `iptables` to run.

mod support;

use rastro::collectors::firewall::{
    BackendReport, ChainName, FirewallBackend, FirewallCollector, FirewallInventory,
    FirewallSource, Ruleset, TableName, iptables_save,
};
use rastro::collectors::kernel_residency::{KernelResidency, Residency};
use rastro_collector::{Collector, Presence};
use rastro_fingerprint::{Content, Observation, Scalar};
use support::observation::{field, keys_of, object_of};

/// A kernel with the legacy tables loaded and nftables merely available, which is the
/// state of the development box before anything provokes it.
const LOADED: &str = "ip_tables 32768 0 - Live 0x0000000000000000\n";

/// Every symbol the firewall backends ask about, all buildable, none compiled in.
const KERNEL_CONFIG: &str = "\
CONFIG_NF_TABLES=m
CONFIG_IP_NF_IPTABLES=m
CONFIG_IP6_NF_IPTABLES=m
";

fn residency() -> KernelResidency {
    KernelResidency::parse(Some(LOADED), Some(KERNEL_CONFIG))
}
/// A dump in the shape `iptables-save` writes: a timestamped header, two tables, a
/// user-defined chain with no policy, and rules in the order the kernel tests them.
const DUMP: &str = "\
# Generated by iptables-save v1.8.9 on Thu Aug 20 09:44:53 2026
*filter
:INPUT DROP [1234:567890]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [98:7654]
:DOCKER-USER - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j DOCKER-USER
COMMIT
# Completed on Thu Aug 20 09:44:53 2026
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 172.17.0.0/16 -j MASQUERADE
COMMIT
";

fn ruleset() -> Ruleset {
    iptables_save::parse(DUMP).expect("this dump is well formed")
}

fn chain(
    ruleset: &Ruleset,
    table: &str,
    chain: &str,
) -> rastro::collectors::firewall::FirewallChain {
    ruleset
        .tables()
        .get(&TableName::new(table).expect("a legal table name"))
        .unwrap_or_else(|| panic!("expected a {table} table"))
        .get(&ChainName::new(chain).expect("a legal chain name"))
        .unwrap_or_else(|| panic!("expected a {chain} chain in {table}"))
        .clone()
}

#[test]
fn parse_reads_a_built_in_chains_policy() {
    // Act: the single most consequential value in the facet.
    let input = chain(&ruleset(), "filter", "INPUT");

    // Assert
    assert_eq!(
        input.policy.as_ref().map(|policy| policy.as_str()),
        Some("DROP")
    );
}

#[test]
fn parse_records_a_user_defined_chain_as_having_no_policy() {
    // Act: `iptables-save` writes `-`, and a chain that falls through to its caller is a
    // different thing from one with a default.
    let docker = chain(&ruleset(), "filter", "DOCKER-USER");

    // Assert
    assert_eq!(docker.policy, None);
}

#[test]
fn parse_keeps_the_rules_in_the_order_the_kernel_tests_them() {
    // Act
    let input = chain(&ruleset(), "filter", "INPUT");

    // Assert: the order is the meaning. Sorting these would put the REJECT first and
    // silently describe a box that drops everything.
    assert_eq!(
        input
            .rules
            .iter()
            .map(|rule| rule.as_str())
            .collect::<Vec<&str>>(),
        [
            "-i lo -j ACCEPT",
            "-p tcp -m tcp --dport 22 -j ACCEPT",
            "-j REJECT --reject-with icmp-host-prohibited"
        ]
    );
}

#[test]
fn parse_reads_every_table_in_the_dump() {
    // Act: the table decides where in the packet path a rule is consulted, so the same
    // rule text in two tables does two different things.
    let ruleset = ruleset();

    // Assert
    assert_eq!(
        ruleset
            .tables()
            .keys()
            .map(|table| table.as_str())
            .collect::<Vec<&str>>(),
        ["filter", "nat"]
    );
}

#[test]
fn parse_files_a_rule_under_the_chain_it_was_appended_to() {
    // Act
    let ruleset = ruleset();

    // Assert
    assert_eq!(chain(&ruleset, "filter", "FORWARD").rules.len(), 1);
    assert_eq!(
        chain(&ruleset, "nat", "POSTROUTING").rules[0].as_str(),
        "-s 172.17.0.0/16 -j MASQUERADE"
    );
}

#[test]
fn parse_drops_the_timestamped_header() {
    // Act: `iptables-save` opens with `# Generated by ... on Thu Aug 20 09:44:53 2026`,
    // and keeping it would make the facet differ between two runs of an untouched box.
    let rendered = format!("{:?}", Observation::from(&ruleset()));

    // Assert
    assert!(
        !rendered.contains("Generated by"),
        "the header must not reach the document, got: {rendered}"
    );
    assert!(!rendered.contains("2026"), "nor its timestamp");
}

#[test]
fn parse_drops_the_packet_and_byte_counters() {
    // Act: they only ever go up, and unlike a DHCP lease there is no stable half worth
    // keeping.
    let rendered = format!("{:?}", Observation::from(&ruleset()));

    // Assert
    assert!(
        !rendered.contains("1234") && !rendered.contains("567890"),
        "a counter must not reach the document, got: {rendered}"
    );
}

#[test]
fn parse_reads_an_empty_dump_as_a_box_that_filters_nothing() {
    // Act: measured on the development box — zero bytes, exit status zero, nothing on
    // stderr.
    let ruleset = iptables_save::parse("").expect("no output is not a failure");

    // Assert
    assert!(ruleset.is_empty());
}

#[test]
fn parse_refuses_a_rule_before_any_table_was_opened() {
    // Act
    let result = iptables_save::parse("-A INPUT -j ACCEPT\n");

    // Assert
    let failure = result.expect_err("a rule with no table must not be accepted");
    assert!(
        failure.to_string().contains("before any table"),
        "the message must say what was wrong, got: {failure}"
    );
}

#[test]
fn parse_refuses_a_rule_for_a_chain_the_dump_never_declared() {
    // Act: `iptables-save` writes every `:` line for a table before any `-A` line in it,
    // so this means the dump was misread, and creating the chain would paper over that.
    let result = iptables_save::parse("*filter\n:INPUT ACCEPT [0:0]\n-A UNDECLARED -j DROP\n");

    // Assert
    let failure = result.expect_err("an undeclared chain must not be invented");
    assert!(
        failure.to_string().contains("UNDECLARED"),
        "the message must name the chain, got: {failure}"
    );
}

#[test]
fn parse_refuses_a_line_the_grammar_does_not_know() {
    // Act: a firewall rule rastro silently dropped is the worst kind of incompleteness.
    let result = iptables_save::parse("*filter\n:INPUT ACCEPT [0:0]\nsomething unexpected\n");

    // Assert
    assert!(result.is_err());
}

#[test]
fn parse_refuses_a_table_dumped_twice() {
    // Act
    let result = iptables_save::parse(
        "*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n*filter\n:INPUT DROP [0:0]\nCOMMIT\n",
    );

    // Assert
    assert!(result.is_err());
}

#[test]
fn the_inventory_tells_an_empty_ruleset_apart_from_a_subsystem_that_cannot_hold_one() {
    // Arrange: the legacy interface was read and filters nothing; the nftables one was
    // never loaded, so it cannot be holding rules at all.
    let found = vec![
        (
            FirewallBackend::IptablesLegacy,
            BackendReport::Read(Ruleset::default()),
        ),
        (FirewallBackend::IptablesNft, BackendReport::SubsystemAbsent),
    ];

    // Act
    let observation = Observation::from(&FirewallInventory::new(found).expect("two backends"));
    let legacy = field(&observation, "iptables_legacy");
    let nft = field(&observation, "iptables_nft");

    // Assert: both report no rules, and the status says how each is known. `ok` is a tool
    // that ran; `absent` is a kernel that cannot hold the state. Collapsing them would
    // make an unread firewall indistinguishable from an unconfigured one.
    assert_eq!(
        field(&legacy, "status").content(),
        &Content::Scalar(Scalar::Text("ok".to_owned()))
    );
    assert_eq!(object_of(&field(&legacy, "tables")), Vec::new());
    assert_eq!(
        field(&nft, "status").content(),
        &Content::Scalar(Scalar::Text("absent".to_owned()))
    );
    assert_eq!(object_of(&field(&nft, "tables")), Vec::new());
}

#[test]
fn the_inventory_refuses_a_backend_reported_twice() {
    // Arrange
    let found = vec![
        (
            FirewallBackend::IptablesLegacy,
            BackendReport::Read(Ruleset::default()),
        ),
        (
            FirewallBackend::IptablesLegacy,
            BackendReport::Read(Ruleset::default()),
        ),
    ];

    // Act & Assert
    assert!(FirewallInventory::new(found).is_err());
}

#[test]
fn a_chain_renders_its_policy_and_its_rules() {
    // Act
    let observation = Observation::from(&ruleset());
    let input = field(&field(&observation, "filter"), "INPUT");

    // Assert
    assert_eq!(keys_of(&input), ["policy", "rules"]);
    assert_eq!(
        field(&input, "policy").content(),
        &Content::Scalar(Scalar::Text("DROP".to_owned()))
    );
}

#[test]
fn presence_is_always_present_because_the_subject_is_what_rastro_can_read() {
    // Act & Assert: a box with no `iptables-save` is not a box that filters nothing.
    assert_eq!(
        FirewallCollector::reading(Vec::new()).presence(),
        Presence::Present
    );
}

#[test]
fn collect_reports_a_key_per_interface_even_with_nothing_found() {
    // Act
    let collected = FirewallCollector::reading(Vec::new())
        .collect()
        .expect("reporting nothing found is not a failure");

    // Assert
    assert_eq!(
        keys_of(&collected),
        [
            "ip6tables_legacy",
            "ip6tables_nft",
            "iptables_legacy",
            "iptables_nft"
        ]
    );
}

#[test]
fn a_backend_reads_through_the_program_that_names_its_own_subsystem() {
    // Arrange: `iptables-save` is a symlink managed by alternatives, and on Debian 12 it
    // points at `iptables-nft`. Running it makes the kernel load `nf_tables`, so rastro
    // asks the backends by name and never through the symlink.

    // Act
    let programs: Vec<&str> = FirewallBackend::ALL
        .into_iter()
        .map(|backend| backend.program())
        .collect();

    // Assert
    assert_eq!(
        programs,
        [
            "ip6tables-legacy-save",
            "ip6tables-nft-save",
            "iptables-legacy-save",
            "iptables-nft-save"
        ]
    );
    assert!(
        !programs.contains(&"iptables-save"),
        "the alternatives symlink is exactly what must not be run"
    );
}

#[test]
fn a_subsystem_the_kernel_never_loaded_is_reported_without_running_anything() {
    // Arrange: `nf_tables` is buildable and unloaded, so no nftables ruleset exists and
    // asking would be the thing that created one.
    let sources = FirewallSource::detect_all(&residency());
    let nft = sources
        .iter()
        .find(|source| source.backend() == FirewallBackend::IptablesNft)
        .expect("every backend is reported");

    // Act
    let report = nft.read();

    // Assert
    assert_eq!(report, BackendReport::SubsystemAbsent);
}

#[test]
fn an_unreadable_kernel_configuration_is_an_error_not_an_empty_ruleset() {
    // Arrange: no `/boot/config-<release>`, so an unloaded subsystem might still be
    // compiled in and holding rules. Reporting `absent` here would describe a filtered box
    // as an unfiltered one.
    let blind = KernelResidency::parse(Some(""), None);
    let sources = FirewallSource::detect_all(&blind);
    let nft = sources
        .iter()
        .find(|source| source.backend() == FirewallBackend::IptablesNft)
        .expect("every backend is reported");

    // Act
    let report = nft.read();

    // Assert
    let BackendReport::Unreadable(reason) = report else {
        panic!("an undetermined subsystem must be loud, got: {report:?}");
    };
    assert!(
        reason.contains("kernel configuration"),
        "the reason must say what could not be read, got: {reason}"
    );
}

#[test]
fn a_resident_subsystem_whose_tool_is_missing_is_an_error() {
    // Arrange: `ip_tables` is loaded, so rules may well exist, and with no program to dump
    // them rastro cannot see them. That is the one case where silence would hide a
    // firewall, so the tool is withheld here rather than left to the build host.
    let source = FirewallSource::using(FirewallBackend::IptablesLegacy, Residency::Loaded, None);

    // Act
    let report = source.read();

    // Assert
    let BackendReport::Unreadable(reason) = report else {
        panic!("a loaded subsystem rastro cannot dump must be loud, got: {report:?}");
    };
    assert!(
        reason.contains("iptables-legacy-save") && reason.contains("ip_tables"),
        "the reason must name both the program and the subsystem, got: {reason}"
    );
}

#[test]
fn an_absent_subsystem_is_reported_even_when_its_tool_is_installed() {
    // Arrange: the tool being present is not a reason to run it. `nf_tables` is unloaded,
    // so there are no rules, and running the dump is what would create the subsystem.
    let source = FirewallSource::using(FirewallBackend::IptablesNft, Residency::Absent, None);

    // Act & Assert
    assert_eq!(source.read(), BackendReport::SubsystemAbsent);
}

#[test]
fn a_subsystem_compiled_into_the_kernel_is_read_rather_than_assumed_empty() {
    // Arrange: a kernel built with `CONFIG_NF_TABLES=y` never lists the module, and rules
    // in it are perfectly real. Treating "not in /proc/modules" as "no rules" would miss
    // them entirely.
    let source = FirewallSource::using(FirewallBackend::IptablesNft, Residency::BuiltIn, None);

    // Act
    let report = source.read();

    // Assert: no tool here, so it lands on the loud path rather than on `absent`.
    assert!(matches!(report, BackendReport::Unreadable(_)));
}

#[test]
fn every_backend_is_reported_so_the_document_shape_never_moves() {
    // Act
    let sources = FirewallSource::detect_all(&residency());

    // Assert
    assert_eq!(sources.len(), FirewallBackend::ALL.len());
}

#[test]
fn the_two_families_share_the_nftables_subsystem_and_not_the_legacy_one() {
    // Assert: one `nf_tables` serves both families, so loading it for IPv4 would have
    // loaded it for IPv6 too. The legacy tables are a module each.
    assert_eq!(
        FirewallBackend::IptablesNft.subsystem().module(),
        FirewallBackend::Ip6tablesNft.subsystem().module()
    );
    assert_ne!(
        FirewallBackend::IptablesLegacy.subsystem().module(),
        FirewallBackend::Ip6tablesLegacy.subsystem().module()
    );
}
