//! Reading the packet filter, without needing an `iptables` to run.

mod support;

use rastro::collectors::firewall::{
    ChainName, FirewallBackend, FirewallCollector, FirewallInventory, Ruleset, TableName,
    iptables_save,
};
use rastro_collector::{Collector, Presence};
use rastro_fingerprint::{Content, Observation, Scalar};
use support::observation::{field, keys_of, object_of};
/// A dump in the shape `iptables-save` writes: a timestamped header, two tables, a
/// user-defined chain with no policy, and rules in the order the kernel tests them.
const DUMP: &str = "\
# Generated by iptables-save v1.8.9 on Thu Aug 20 09:44:53 2026
*filter
:INPUT DROP [1234:567890]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [98:7654]
:DOCKER-USER - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j DOCKER-USER
COMMIT
# Completed on Thu Aug 20 09:44:53 2026
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 172.17.0.0/16 -j MASQUERADE
COMMIT
";

fn ruleset() -> Ruleset {
    iptables_save::parse(DUMP).expect("this dump is well formed")
}

fn chain(
    ruleset: &Ruleset,
    table: &str,
    chain: &str,
) -> rastro::collectors::firewall::FirewallChain {
    ruleset
        .tables()
        .get(&TableName::new(table).expect("a legal table name"))
        .unwrap_or_else(|| panic!("expected a {table} table"))
        .get(&ChainName::new(chain).expect("a legal chain name"))
        .unwrap_or_else(|| panic!("expected a {chain} chain in {table}"))
        .clone()
}

#[test]
fn parse_reads_a_built_in_chains_policy() {
    // Act: the single most consequential value in the facet.
    let input = chain(&ruleset(), "filter", "INPUT");

    // Assert
    assert_eq!(
        input.policy.as_ref().map(|policy| policy.as_str()),
        Some("DROP")
    );
}

#[test]
fn parse_records_a_user_defined_chain_as_having_no_policy() {
    // Act: `iptables-save` writes `-`, and a chain that falls through to its caller is a
    // different thing from one with a default.
    let docker = chain(&ruleset(), "filter", "DOCKER-USER");

    // Assert
    assert_eq!(docker.policy, None);
}

#[test]
fn parse_keeps_the_rules_in_the_order_the_kernel_tests_them() {
    // Act
    let input = chain(&ruleset(), "filter", "INPUT");

    // Assert: the order is the meaning. Sorting these would put the REJECT first and
    // silently describe a box that drops everything.
    assert_eq!(
        input
            .rules
            .iter()
            .map(|rule| rule.as_str())
            .collect::<Vec<&str>>(),
        [
            "-i lo -j ACCEPT",
            "-p tcp -m tcp --dport 22 -j ACCEPT",
            "-j REJECT --reject-with icmp-host-prohibited"
        ]
    );
}

#[test]
fn parse_reads_every_table_in_the_dump() {
    // Act: the table decides where in the packet path a rule is consulted, so the same
    // rule text in two tables does two different things.
    let ruleset = ruleset();

    // Assert
    assert_eq!(
        ruleset
            .tables()
            .keys()
            .map(|table| table.as_str())
            .collect::<Vec<&str>>(),
        ["filter", "nat"]
    );
}

#[test]
fn parse_files_a_rule_under_the_chain_it_was_appended_to() {
    // Act
    let ruleset = ruleset();

    // Assert
    assert_eq!(chain(&ruleset, "filter", "FORWARD").rules.len(), 1);
    assert_eq!(
        chain(&ruleset, "nat", "POSTROUTING").rules[0].as_str(),
        "-s 172.17.0.0/16 -j MASQUERADE"
    );
}

#[test]
fn parse_drops_the_timestamped_header() {
    // Act: `iptables-save` opens with `# Generated by ... on Thu Aug 20 09:44:53 2026`,
    // and keeping it would make the facet differ between two runs of an untouched box.
    let rendered = format!("{:?}", Observation::from(&ruleset()));

    // Assert
    assert!(
        !rendered.contains("Generated by"),
        "the header must not reach the document, got: {rendered}"
    );
    assert!(!rendered.contains("2026"), "nor its timestamp");
}

#[test]
fn parse_drops_the_packet_and_byte_counters() {
    // Act: they only ever go up, and unlike a DHCP lease there is no stable half worth
    // keeping.
    let rendered = format!("{:?}", Observation::from(&ruleset()));

    // Assert
    assert!(
        !rendered.contains("1234") && !rendered.contains("567890"),
        "a counter must not reach the document, got: {rendered}"
    );
}

#[test]
fn parse_reads_an_empty_dump_as_a_box_that_filters_nothing() {
    // Act: measured on the development box — zero bytes, exit status zero, nothing on
    // stderr.
    let ruleset = iptables_save::parse("").expect("no output is not a failure");

    // Assert
    assert!(ruleset.is_empty());
}

#[test]
fn parse_refuses_a_rule_before_any_table_was_opened() {
    // Act
    let result = iptables_save::parse("-A INPUT -j ACCEPT\n");

    // Assert
    let failure = result.expect_err("a rule with no table must not be accepted");
    assert!(
        failure.to_string().contains("before any table"),
        "the message must say what was wrong, got: {failure}"
    );
}

#[test]
fn parse_refuses_a_rule_for_a_chain_the_dump_never_declared() {
    // Act: `iptables-save` writes every `:` line for a table before any `-A` line in it,
    // so this means the dump was misread, and creating the chain would paper over that.
    let result = iptables_save::parse("*filter\n:INPUT ACCEPT [0:0]\n-A UNDECLARED -j DROP\n");

    // Assert
    let failure = result.expect_err("an undeclared chain must not be invented");
    assert!(
        failure.to_string().contains("UNDECLARED"),
        "the message must name the chain, got: {failure}"
    );
}

#[test]
fn parse_refuses_a_line_the_grammar_does_not_know() {
    // Act: a firewall rule rastro silently dropped is the worst kind of incompleteness.
    let result = iptables_save::parse("*filter\n:INPUT ACCEPT [0:0]\nsomething unexpected\n");

    // Assert
    assert!(result.is_err());
}

#[test]
fn parse_refuses_a_table_dumped_twice() {
    // Act
    let result = iptables_save::parse(
        "*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n*filter\n:INPUT DROP [0:0]\nCOMMIT\n",
    );

    // Assert
    assert!(result.is_err());
}

#[test]
fn the_inventory_tells_an_absent_tool_apart_from_an_empty_ruleset() {
    // Arrange: only the IPv4 interface was found, and it reported nothing.
    let found = vec![(FirewallBackend::Iptables, Ruleset::default())];

    // Act
    let observation = Observation::from(&FirewallInventory::new(found).expect("one backend"));

    // Assert: `null` means the tool is not on the box; an empty object means the tool ran
    // and the box filters nothing. Reading one as the other would report an unprotected
    // box as an unknown one.
    assert_eq!(keys_of(&observation), ["ip6tables", "iptables"]);
    assert_eq!(
        field(&observation, "ip6tables").content(),
        &Content::Scalar(Scalar::Null)
    );
    assert_eq!(object_of(&field(&observation, "iptables")), Vec::new());
}

#[test]
fn the_inventory_refuses_a_backend_reported_twice() {
    // Arrange
    let found = vec![
        (FirewallBackend::Iptables, Ruleset::default()),
        (FirewallBackend::Iptables, Ruleset::default()),
    ];

    // Act & Assert
    assert!(FirewallInventory::new(found).is_err());
}

#[test]
fn a_chain_renders_its_policy_and_its_rules() {
    // Act
    let observation = Observation::from(&ruleset());
    let input = field(&field(&observation, "filter"), "INPUT");

    // Assert
    assert_eq!(keys_of(&input), ["policy", "rules"]);
    assert_eq!(
        field(&input, "policy").content(),
        &Content::Scalar(Scalar::Text("DROP".to_owned()))
    );
}

#[test]
fn presence_is_always_present_because_the_subject_is_what_rastro_can_read() {
    // Act & Assert: a box with no `iptables-save` is not a box that filters nothing.
    assert_eq!(
        FirewallCollector::reading(Vec::new()).presence(),
        Presence::Present
    );
}

#[test]
fn collect_reports_a_key_per_interface_even_with_nothing_found() {
    // Act
    let collected = FirewallCollector::reading(Vec::new())
        .collect()
        .expect("reporting nothing found is not a failure");

    // Assert
    assert_eq!(keys_of(&collected), ["ip6tables", "iptables"]);
}
