//! The `iptables-save` dump format.
//!
//! ```text
//! # Generated by iptables-save v1.8.9 on Thu Aug 20 09:44:53 2026
//! *filter
//! :INPUT ACCEPT [0:0]
//! :FORWARD DROP [0:0]
//! :DOCKER - [0:0]
//! -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
//! COMMIT
//! ```
//!
//! Everything peculiar to this format lives here: a table introduced by `*`, chains
//! declared by `:` with a policy and a counter pair, rules appended with `-A`, and a
//! `COMMIT` terminator.

use std::collections::BTreeMap;

use rastro_collector::CollectionError;

use crate::collectors::firewall::model::{FirewallChain, Ruleset};
use crate::collectors::firewall::value_objects::{
    ChainName, ChainPolicy, RuleSpecification, TableName,
};

/// What introduces a table.
const TABLE: char = '*';

/// What introduces a chain declaration.
const CHAIN: char = ':';

/// What introduces a rule appended to a chain.
const RULE: &str = "-A ";

/// What `iptables-save` writes where a user-defined chain's policy would go.
const NO_POLICY: &str = "-";

/// Translates a dump into the model.
///
/// **The `#` header is skipped, and skipping it is load-bearing rather than tidiness.**
/// `iptables-save` opens its output with `# Generated by iptables-save v1.8.9 on Thu Aug 20
/// 09:44:53 2026`. That timestamp changes on every run, so a parser that kept the comment
/// would make this facet differ between two runs of an untouched box and break the
/// byte-identical guarantee the whole tool rests on.
///
/// **The `[0:0]` counters are dropped at the boundary.** They are the packets and bytes a
/// chain has seen, so they only ever go up. Unlike a DHCP lease there is no stable half
/// worth keeping, so they are read and discarded the way `/proc/mounts` has its constant
/// `dump` and `fsck` columns discarded.
pub fn parse(dump: &str) -> Result<Ruleset, CollectionError> {
    let mut tables: Vec<(TableName, BTreeMap<ChainName, FirewallChain>)> = Vec::new();
    let mut current: Option<(TableName, BTreeMap<ChainName, FirewallChain>)> = None;

    for line in dump.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line == "COMMIT" {
            continue;
        }

        if let Some(name) = line.strip_prefix(TABLE) {
            if let Some(table) = current.take() {
                tables.push(table);
            }
            current = Some((TableName::new(name.trim())?, BTreeMap::new()));
            continue;
        }

        let (_, chains) = current.as_mut().ok_or_else(|| {
            CollectionError::new(format!(
                "{line:?} came before any table was opened, so the dump was misread"
            ))
        })?;

        if let Some(declaration) = line.strip_prefix(CHAIN) {
            let (name, policy) = parse_chain(declaration)?;
            chains.insert(
                name,
                FirewallChain {
                    policy,
                    rules: Vec::new(),
                },
            );
            continue;
        }

        if let Some(rule) = line.strip_prefix(RULE) {
            append_rule(chains, rule)?;
            continue;
        }

        // Anything else is a line this grammar does not know. Refused rather than skipped:
        // a firewall rule rastro silently dropped is the worst kind of incompleteness.
        return Err(CollectionError::new(format!(
            "{line:?} is not a line `iptables-save` writes"
        )));
    }

    if let Some(table) = current.take() {
        tables.push(table);
    }

    Ruleset::new(tables)
}

/// One `:CHAIN POLICY [packets:bytes]` declaration.
fn parse_chain(declaration: &str) -> Result<(ChainName, Option<ChainPolicy>), CollectionError> {
    let mut words = declaration.split_whitespace();
    let name = words.next().ok_or_else(|| {
        CollectionError::new(format!("{declaration:?} declares a chain with no name"))
    })?;
    let policy = words.next().ok_or_else(|| {
        CollectionError::new(format!("{declaration:?} declares a chain with no policy"))
    })?;

    let policy = if policy == NO_POLICY {
        None
    } else {
        Some(ChainPolicy::new(policy)?)
    };

    Ok((ChainName::new(name)?, policy))
}

/// Files a rule under the chain it is appended to.
///
/// **The chain must already have been declared**, and that ordering is guaranteed by the
/// format rather than assumed: `iptables-save` writes every `:` line for a table before any
/// `-A` line in it. A rule for an undeclared chain therefore means the dump was misread, and
/// creating the chain on the fly would paper over exactly that.
fn append_rule(
    chains: &mut BTreeMap<ChainName, FirewallChain>,
    rule: &str,
) -> Result<(), CollectionError> {
    let (chain, specification) = rule.split_once(char::is_whitespace).ok_or_else(|| {
        CollectionError::new(format!("{rule:?} names a chain but carries no rule"))
    })?;

    let chain = ChainName::new(chain)?;
    let target = chains.get_mut(&chain).ok_or_else(|| {
        CollectionError::new(format!(
            "a rule was appended to the chain {:?}, which the dump never declared",
            chain.as_str()
        ))
    })?;

    target
        .rules
        .push(RuleSpecification::new(specification.trim())?);

    Ok(())
}
